apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: streamlit-port
  type: NodePort